### ISSUE TITLE
GFX: hud colour mismatch issue 

### ISSUE THREAD

**Issue by lavenderdotpet** [lavenderdotpet/LibreQuake#219]
![image](https://github.com/user-attachments/assets/8ce8a5cf-4952-40da-a1ea-a58d973bc352)
## as seen above the ammo icons are based on an older version of the hud before it was made orange

**Comment by Zungrysoft** [comment]
Yeah, I think I used the older version of the HUD for that part since the newer HUD didn't have the dividing lines between the weapons. I didn't notice the color difference.

I still have the .kra files for this, so I could re-export them with the correct color if you provide me with the correct background image.

**Comment by lavenderdotpet** [comment]
oh that would make the work alot easier ill get that to u soon

**Comment by lavenderdotpet** [comment]
![IBAR](https://github.com/user-attachments/assets/29457fcd-8274-4126-af28-2d7052564547)
@Zungrysoft
